### ISSUE TITLE
Naverlogin.deleteToken()이 정상동작하지 않습니다.

### ISSUE THREAD

**Issue by rivernine** [crossplatformkorea/react-native-naver-login#156]
### Description

현재 다음의 버전을 사용하고 있습니다.
"@react-native-seoul/naver-login": "^3.0.0-rc.1",

디바이스가 아닌 시뮬레이터를 사용하고 있고, IOS15.5 입니다.

----------------------------------------------------------------------------------------

IOS에서 로그인하여 Profile정보를 가져온 후 `logout()`, `deleteToken()`을 진행하고 있습니다.
하지만 `deleteToken()`이 정상작동하지 않아 로그인정보가 계속 남아있습니다.

`await deleteToken()` 후의 로직이 실행되지 않는 것으로 보아 해당 메소드의 응답을 받지 못하고 있습니다.

검토부탁드립니다.

### Steps to reproduce

1.
```js
console.log('start deleteToken()')
try {
  await NaverLogin.deleteToken();
  console.log('complete')
} catch (e) {
  console.error(e);
}
```

2.
```bash
>> deleteToken
```

### Snack or a link to a repository

empty

### React Native Naver Login version

^3.0.0-rc.1

### React Native version

0.70.3

### Platforms

iOS

### Device

iOS simulator

### Device model

IOS15.5

### Acknowledgements

Yes

**Comment by devsince2021** [comment]
안드로이드에서도 크래시가 발생합니다

  kotlin.UninitializedPropertyAccessException: lateinit property applicationContext has not been initialized
        at com.navercorp.nid.NaverIdLoginSDK.getApplicationContext(NaverIdLoginSDK.kt:41)
        at com.navercorp.nid.oauth.EncryptedPreferences.getCtx(EncryptedPreferences.kt:20)
        at com.navercorp.nid.oauth.EncryptedPreferences.init(EncryptedPreferences.kt:35)
        at com.navercorp.nid.oauth.EncryptedPreferences.access$init(EncryptedPreferences.kt:17)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:30)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:29)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:29)
        at com.navercorp.nid.oauth.EncryptedPreferences.set(EncryptedPreferences.kt:80)
        at com.navercorp.nid.oauth.NidOAuthPreferencesManager.setAccessToken(NidOAuthPreferencesManager.kt:16)
        at com.navercorp.nid.NaverIdLoginSDK.logout(NaverIdLoginSDK.kt:137)
        at com.navercorp.nid.oauth.NidOAuthLogin$callDeleteTokenApi$1.invokeSuspend(NidOAuthLogin.kt:136)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a788a3b, Dispatchers.Main]

**Comment by siabard** [comment]
> NaverIdLoginSDK

이 경우는 네이버 계정으로 로그인하고 해당 앱을 메모리에서만 지웠을 때 재현되네요.
네이버 context 가 생성되어있지않아 생기는 이슈가 아닌가 생각됩니다.

`NidOAuthLogin().callDeleteTokenApi` 호출시  `NaverIdLoginSDK.initialize(...)` 로 초기화가 되지않는 상황에서 실행되는 현상같습니다. 
일단 naver login sdk 가 초기화되었는지 알 수 없다보니 문제가 발생할 수 밖에 없는 구조같습니다.
login sdk 를 초기화하는 루틴과 login 하는 루틴을 분리해서 앱 실행시 sdk를 초기화시킬 수 있도록 코드가 변경되어야할 것 같습니다. 아니면 현재 naver login sdk 가 설정되었는지 알려주거나요..

3.0 에서는 바뀌었는지 모르겠네요.

**Comment by ungveloper** [comment]
1년이 다 되어가는데 이 문제는 아직도 해결되지 않았나보네요.

**Comment by hyochan** [comment]
@ungveloper #166 이거 테스트 해보셨나요? 해보셨으면 코멘트 등도 달아주시면 도움이 될 것 같네요.

참고로, https://sapegin.me/blog/open-source-no-more 이 글을 한 번 읽어보시면 좋을 것 같아요. 최근에 많은 우수한 오픈소스 참여자들이 생태계에서 멀어지는 추세를 보며, 그 원인과 해결 방법에 대한 생각을 공유하고 싶습니다.  건강한 생태계는 항상 개인의 인식과 참여에 크게 좌우되니, 생태계의 지속 가능성을 위해서 인지하시면 좋을 것 같아요.

**Comment by ungveloper** [comment]
@hyochan 우선 훌륭한 오픈 소스를 제공해 주셔서 진심으로 감사의 말씀드립니다.

말씀해 주신 대로 최초 로그인 이후 다시 앱을 실행시켜 로그아웃을 시도하면
"NaverIdLoginSDK가 초기화되기 전에 deleteToken이 먼저 실행되면서 앱이 강제로 종료되는 문제"를 확인하였고,
남겨주신 링크를 통해 테스트해 보았지만 아쉽게도 문제가 해결되지는 않았습니다.

적용을 잘못했을지도 모른다는 가능성을 염두에 둔 채 우선은 "await NaverLogin.deleteToken()"이 실행되기 전에
"await NaverLogin.login()"을 먼저 실행시키는 것으로 조치를 하였습니다.

이후 조치가 된다면 다시 한번 코멘트 남기도록 하겠습니다.

다시 한번 감사의 말씀드립니다 :)

**Comment by ungveloper** [comment]
@hyochan 우선 훌륭한 오픈 소스를 제공해 주셔서 진심으로 감사의 말씀드립니다.

[남겨주신 대로](https://github.com/crossplatformkorea/react-native-naver-login/pull/166) 최초 로그인 이후 다시 앱을 실행시켜 로그아웃을 시도하면
"NaverIdLoginSDK가 초기화되기 전에 deleteToken이 먼저 실행되면서 앱이 강제로 종료되는 문제"를 확인하였고,
남겨주신 링크를 통해 테스트해 보았지만 아쉽게도 문제가 해결되지는 않았습니다.

적용을 잘못했을지도 모른다는 가능성을 염두에 둔 채 우선은 "await NaverLogin.deleteToken()"이 실행되기 전에
"await NaverLogin.login()"을 먼저 실행시키는 것으로 조치를 하였습니다.

이후 조치가 된다면 다시 한번 코멘트 남기도록 하겠습니다.

다시 한번 감사의 말씀드립니다 :)

**Comment by hyochan** [comment]
@ungveloper 감사합니다. 개발하면서 도움이 될 만한 경험이나 방향 혹은 테스트 결과 등만 잘 thread에 남겨도 다음 오신 분들에게 더 많은 도움을 드릴 수 있을 것 같아요.

**Comment by mym0404** [comment]
안녕하세요, 제보 감사드립니다. 이 쓰레드에서 논의되고있는 SDK 초기화라는 것이 어떤건지에 대한 정의가 필요할 것 같습니다.

우선, 네아로 SDK는 Android, iOS 모두 SDK 를 초기화시켜야 한다는 로직은 포함하고 있지 않습니다. 따라서 이 라이브러리도 어떤 초기화로직의 API도 포함하지 않습니다.

이전에 `3.0.0.rc`에 잠깐 Android에 `initialize`가 추가된건 native SDK `5.2.0`에서 특이한(Android Context의 Lifecycle을 인자로 넘겨줘야하는? 으로 기억합니다.) 로그인 콜백함수를 써야해서 어쩔 수 없는 API였고 그 이후 `5.3.0`에서 이것이 개선되어 다시 제거했습니다.

**Comment by mym0404** [comment]
안녕하세요, 제보 감사드립니다. 이 쓰레드에서 논의되고있는 SDK 초기화라는 것이 어떤건지에 대한 정의가 필요할 것 같습니다.

아니면 단순히 한 프로세스 사이클에서 `login`이 성공하지 않은 상태에서 `deleteToken`을 호출하면 크래시가 난다고 말씀하시는걸까요?

> 이전에 `3.0.0.rc`에 잠깐 Android에 `initialize`가 추가된건 native SDK `5.2.0`에서 특이한(Android Context의 Lifecycle을 인자로 넘겨줘야하는? 으로 기억합니다.) 로그인 콜백함수를 써야해서 어쩔 수 없는 API였고 그 이후 `5.3.0`에서 이것이 개선되어 다시 제거했습니다.

>[!NOTE]
>여기서부터 말하는 초기화는 `initialise` 같은 Naver SDK 내부 함수의 호출을 말합니다.

이 패키지에선 예전부터 Android, iOS초기화를 명시적으로 해주지않고 `login`인 시에만 해주도록 되어있는데, 그것이 문제가 된 것 같습니다.

----
iOS에서만 단순히 확인해보았는데, 확실히 한 프로세스 사이클에서 `login`에 성공하지 않은 채로 `deleteToken`을 호출할 시 제대로 동작되지 않는것같습니다.

Android는 모르겠지만 iOS는 Github Release엔 `4.1.5`(현재 이 패키지의 버전)SDK가 최신이지만 커밋을 보니 `4.2`도 보이는 것 같고, 코드는 Github에 제대로 포함도 되어있지 않은것같습니다. (왜 xcodeframework 자체를 올려놓은건지는 의문이네요)
----

Android, iOS 둘다 native SDK 버전을 올리며 다시 명시적 초기화 로직을 모두 삽입시켜두어야겠습니다.

@hyochan

이것이 4.x 로의 BREAKING CHANGE가 되어야 할진 잘 모르겠습니다.

이미 명시적 초기화를 해주지 않고 사용하던 것엔 문제가 없다고 판단이 되어서 3.1.0정도로 버전을 올려도 될것같은데 어떠신가요?
