### ISSUE TITLE
android 에서 처음 로그인 시도 시, 로그인이 안되는 현상

### ISSUE THREAD

**Issue by wooiron** [crossplatformkorea/react-native-naver-login#158]
### Description

android 에서 어플리케이션을 빌드 후 처음으로 네이버로 로그인 함수를 실행하면 로그인이 되지 않는 현상이 발생합니다.(ios 는 정상 작동 됨)

함수를 다시 한번 더 실행하면 그때는 정상적으로 작동이됩니다.

```jsx
export const getNaverAccessToken = async () => {
  try {
    // NaverLogin.login 실행 시 문제 발생
    const {
      isSuccess = false,
      failureResponse,
      successResponse,
    } = await NaverLogin.login({
      appName,
      consumerKey,
      consumerSecret,
      serviceUrlScheme,
    });
    
    // !!! 로그가 출력되지 않고 함수가 종료됩니다.
    console.log('NaverLogin.login 실행 완료')
    
    if (isSuccess) {
      return successResponse.accessToken;
    }
    console.log('naver 로그인 실패!');
    console.log({ failureResponse });
  } catch (e) {
    // catch 내의 코드도 실행이 되지 않습니다.
    console.error(e);
  }

  return null;
};
```

android studio 를 통하여 디버깅을 한 결과 아래와 같은 문제가 발생하는 것을 확인하였습니다.
```
2022-12-05 16:56:36.758 10380-10380/com.stylerecipe W/AndroidKeysetManager: keyset not found, will generate a new one
    java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_key_keyset__ does not exist
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
        at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
        at com.navercorp.nid.oauth.EncryptedPreferences.init(EncryptedPreferences.kt:34)
        at com.navercorp.nid.oauth.EncryptedPreferences.access$init(EncryptedPreferences.kt:17)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:30)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:29)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:29)
        at com.navercorp.nid.oauth.EncryptedPreferences.get(EncryptedPreferences.kt:86)
        at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.kt:53)
        at com.navercorp.nid.oauth.EncryptedPreferences.migration(EncryptedPreferences.kt:112)
        at com.navercorp.nid.oauth.EncryptedPreferences.setContext(EncryptedPreferences.kt:46)
        at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:53)
        at com.dooboolab.naverlogin.RNNaverLoginModule.login$lambda-1(RNNaverLoginModule.kt:66)
        at com.dooboolab.naverlogin.RNNaverLoginModule.lambda$9DhD-bSQORgiqNoOhxh4y3p9nl8(Unknown Source:0)
        at com.dooboolab.naverlogin.-$$Lambda$RNNaverLoginModule$9DhD-bSQORgiqNoOhxh4y3p9nl8.run(Unknown Source:10)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2022-12-05 16:56:36.871 10380-10380/com.stylerecipe W/AndroidKeysetManager: keyset not found, will generate a new one
    java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_value_keyset__ does not exist
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
        at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:311)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:160)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
        at com.navercorp.nid.oauth.EncryptedPreferences.init(EncryptedPreferences.kt:34)
        at com.navercorp.nid.oauth.EncryptedPreferences.access$init(EncryptedPreferences.kt:17)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:30)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:29)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:29)
        at com.navercorp.nid.oauth.EncryptedPreferences.get(EncryptedPreferences.kt:86)
        at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.kt:53)
        at com.navercorp.nid.oauth.EncryptedPreferences.migration(EncryptedPreferences.kt:112)
        at com.navercorp.nid.oauth.EncryptedPreferences.setContext(EncryptedPreferences.kt:46)
        at com.navercorp.nid.NaverIdLoginSDK.initialize(NaverIdLoginSDK.kt:53)
        at com.dooboolab.naverlogin.RNNaverLoginModule.login$lambda-1(RNNaverLoginModule.kt:66)
        at com.dooboolab.naverlogin.RNNaverLoginModule.lambda$9DhD-bSQORgiqNoOhxh4y3p9nl8(Unknown Source:0)
        at com.dooboolab.naverlogin.-$$Lambda$RNNaverLoginModule$9DhD-bSQORgiqNoOhxh4y3p9nl8.run(Unknown Source:10)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

### Steps to reproduce

1. NaverLogin.login() 함수 실행 시 android 에서 문제 발생

### React Native Naver Login version

3.0.0-rc.1

### React Native version

0.64.2

### Platforms

Android

### JavaScript runtime

None

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Device model

Samsung Galaxy note 9

### Acknowledgements

Yes

**Comment by mym0404** [comment]
https://github.com/naver/naveridlogin-sdk-android/issues/67
와 같은 문제로 보입니다.

**Comment by hoon9144** [comment]
안녕하세요 같은문제로 골머리가 아픈데 혹시 해결하셨나요? 라이브러리 
업데이트가 방법이 아닌거같아서요ㅜ
