### ISSUE TITLE
Login 시도시 크래쉬

### ISSUE THREAD

**Issue by mk0116** [crossplatformkorea/react-native-naver-login#168]
### Description

2023-04-10 21:28:24.665 14202-14202/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.aienglish, PID: 14202
    java.lang.RuntimeException: Unable to start activity ComponentInfo{co.aienglish/com.navercorp.nid.oauth.activity.NidOAuthCustomTabActivity}: kotlin.UninitializedPropertyAccessException: lateinit property context has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3679)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3816)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:99)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2299)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7850)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property context has not been initialized
        at com.navercorp.nid.oauth.EncryptedPreferences.init(EncryptedPreferences.kt:33)
        at com.navercorp.nid.oauth.EncryptedPreferences.access$init(EncryptedPreferences.kt:16)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:28)
        at com.navercorp.nid.oauth.EncryptedPreferences$encryptedPreferences$2.invoke(EncryptedPreferences.kt:27)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.navercorp.nid.oauth.EncryptedPreferences.getEncryptedPreferences(EncryptedPreferences.kt:27)
        at com.navercorp.nid.oauth.EncryptedPreferences.get(EncryptedPreferences.kt:84)
        at com.navercorp.nid.oauth.NidOAuthPreferencesManager.getClientId(NidOAuthPreferencesManager.kt:53)
        at com.navercorp.nid.oauth.NidOAuthQuery$Builder.<init>(NidOAuthQuery.kt:34)
        at com.navercorp.nid.oauth.activity.NidOAuthCustomTabActivity.init(NidOAuthCustomTabActivity.kt:37)
        at com.navercorp.nid.oauth.activity.NidOAuthCustomTabActivity.onCreate(NidOAuthCustomTabActivity.kt:29)
        at android.app.Activity.performCreate(Activity.java:8257)
        at android.app.Activity.performCreate(Activity.java:8237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1339)

### Steps to reproduce

1. 로그인 시도를 위해 NaverLogin.login 메소드 호출
2. 크래쉬

### Snack or a link to a repository

--

### React Native Naver Login version

2.3.0

### React Native version

0.70.8

### Platforms

Android

### JavaScript runtime

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by mym0404** [comment]
안녕하세요, 리포팅 감사합니다.

현재 버전인 3.0.0에서 실제 디바이스, Release Build로 시도해보시고 이슈가 계속된다면

reproducible sample을 올려주시면 감사하겠습니다.
